## Copyright 2009-2020 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

stages:
  - build
  - package
  - scan_source

.base:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    OIDN_ROOT_DIR:          "$CI_PROJECT_DIR"
    PYTHONUNBUFFERED:       1

.build:
  stage: build
  only:
    - pushes
    - schedules
    - web
  artifacts:
    untracked: true
    name:      "$CI_JOB_NAME"
    when:      always
    expire_in: 1d

.package:
  stage:  package
  script: scripts/release.py package
  only:
    - schedules
    - web
  artifacts:
    paths:
      - build_release/*.tar.gz
      - build_release/*.zip
    name:      "$CI_JOB_NAME"
    expire_in: 1d

## -----------------------------------------------------------------------------
## Linux
## -----------------------------------------------------------------------------
 
.base-linux:
  extends: .base
  tags:
    - docker

.build-linux:
  extends:
    - .build
    - .base-linux

.package-linux:
  extends:
    - .package
    - .base-linux

## -----------------------------------------------------------------------------

.centos7:
  image: openimagedenoise/build:centos7
  
build-centos7-icc:
  extends:
    - .build-linux
    - .centos7
  script: scripts/release.py build --compiler icc

package-linux:
  extends:
    - .package-linux
    - .centos7
  needs: 
    - job: build-centos7-icc
      artifacts: true

## -----------------------------------------------------------------------------

.ubuntu18.04:
  image: openimagedenoise/build:ubuntu18.04

build-ubuntu18.04-gcc:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/release.py build --compiler gcc

build-ubuntu18.04-gcc-debug:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/release.py build --compiler gcc --config Debug

build-ubuntu18.04-clang:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/release.py build --compiler clang

#ubuntu18.04-kw-gcc-build:
#  extends:      [ .ubuntu18.04, .build-linux ]
#  script:       "scripts/klocwork_build.sh"


## -----------------------------------------------------------------------------
## macOS
## -----------------------------------------------------------------------------

.base-macos:
  extends: .base
  tags:
    - osx

.build-macos:
  extends:
    - .build
    - .base-macos

.package-macos:
  extends:
    - .package
    - .base-macos

## -----------------------------------------------------------------------------

build-macos-icc:
  extends: .build-macos
  script:  scripts/release.py build --compiler icc

build-macos-clang:
  extends: .build-macos
  script:  scripts/release.py build --compiler clang

package-macos:
  extends: .package-macos
  needs: 
    - job: build-macos-icc
      artifacts: true

## -----------------------------------------------------------------------------
## Windows
## -----------------------------------------------------------------------------

.base-windows:
  extends: .base
  tags:
    - win10
    - msvc15
    - icc19
  variables:
    ErrorActionPreference: stop

.build-windows:
  extends:
    - .build
    - .base-windows

.package-windows:
  extends:
    - .package
    - .base-windows

## -----------------------------------------------------------------------------

build-windows-icc:
  extends: .build-windows
  script:  python scripts/release.py build --compiler icc

build-windows-msvc:
  extends: .build-windows
  script:  python scripts/release.py build --compiler msvc

build-windows-msvc-debug:
  extends: .build-windows
  script:  python scripts/release.py build --compiler msvc --config Debug

package-windows:
  extends: .package-windows
  needs:
    - job: build-windows-icc
      artifacts: true
      
## -----------------------------------------------------------------------------
## Protex
## -----------------------------------------------------------------------------

protex_scan:
  stage:  scan_source
  tags:
    - docker
  only:
    - schedules
    - web
  script: scripts/protex_scan.sh
  image:  amd64/openjdk:8
  dependencies: []
  # Will fail regularly, do not break nightlies because of that.
  allow_failure: true
  artifacts:
    paths:     [ "$CI_PROJECT_DIR/ip_protex.log" ]
    name:      "$CI_JOB_NAME"
    when:      always
    expire_in: 7d
