## Copyright 2009-2020 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

stages:
  - build
  - test
  - deploy
  - scan

.base:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    OIDN_ROOT_DIR:          "$CI_PROJECT_DIR"
    PYTHONUNBUFFERED:       1

.build:
  stage: build
  only:
    - pushes
    - schedules
    - web
  artifacts:
    name: "$CI_JOB_NAME"
    untracked: true
    when: always
    expire_in: 3 days

.test:
  stage: test
  only:
    - pushes
    - schedules
    - web
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - test.log
    when: always
    expire_in: 3 days

.package:
  stage: deploy
  only:
    - schedules
    - web
  dependencies: []
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/*.tar.gz
      - build/*.zip
    expire_in: 1 week

## -----------------------------------------------------------------------------
## Linux
## -----------------------------------------------------------------------------

.base-linux:
  extends: .base
  tags:
    - docker

.build-linux:
  extends:
    - .build
    - .base-linux

.test-linux:
  extends:
    - .test
    - .base-linux

.package-linux:
  extends:
    - .package
    - .base-linux

## -----------------------------------------------------------------------------

.centos7:
  image: openimagedenoise/build:centos7
  
build-centos7-icc:
  extends:
    - .build-linux
    - .centos7
  script: scripts/build.py install --compiler icc

test-centos7-icc-avx512:
  extends:
    - .test-linux
    - .centos7
  needs:
    - job: build-centos7-icc
      artifacts: true
  tags:
    - avx512vl
  script: scripts/test.py

test-centos7-icc-knl:
  extends:
    - .test-linux
    - .centos7
  needs:
    - job: build-centos7-icc
      artifacts: true
  tags:
    - knl
  script: scripts/test.py

test-centos7-icc-avx2:
  extends:
    - .test-linux
    - .centos7
  needs:
    - job: build-centos7-icc
      artifacts: true
  tags:
    - avx2
  script: scripts/test.py

test-centos7-icc-sse4:
  extends:
    - .test-linux
    - .centos7
  needs:
    - job: build-centos7-icc
      artifacts: true
  script: scripts/test.py --arch pnr

package-linux:
  extends:
    - .package-linux
    - .centos7
  script: scripts/build.py package

## -----------------------------------------------------------------------------

.ubuntu18.04:
  image: openimagedenoise/build:ubuntu18.04

build-ubuntu18.04-gcc:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/build.py install --compiler gcc

test-ubuntu18.04-gcc:
  extends:
    - .test-linux
    - .ubuntu18.04
  needs:
    - job: build-ubuntu18.04-gcc
      artifacts: true
  script: scripts/test.py

build-ubuntu18.04-gcc-debug:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/build.py install --compiler gcc --config Debug

test-ubuntu18.04-gcc-debug:
  extends:
    - .test-linux
    - .ubuntu18.04
  needs:
    - job: build-ubuntu18.04-gcc-debug
      artifacts: true
  script: scripts/test.py

build-ubuntu18.04-gcc-static:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/build.py --compiler gcc -D OIDN_STATIC_LIB=ON

build-ubuntu18.04-clang:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/build.py --compiler clang

build-ubuntu18.04-kw-gcc:
  extends:
    - .build-linux
    - .ubuntu18.04
  script: scripts/klocwork_build.sh

## -----------------------------------------------------------------------------

.ubuntu20.04:
  image: openimagedenoise/build:ubuntu20.04

build-ubuntu20.04-gcc:
  extends:
    - .build-linux
    - .ubuntu20.04
  script:
    - mkdir build
    - cd build
    - cmake .. -D OIDN_APPS_OPENIMAGEIO=ON
    - make -j VERBOSE=1

## -----------------------------------------------------------------------------
## macOS
## -----------------------------------------------------------------------------

.base-macos:
  extends: .base
  tags:
    - osx

.build-macos:
  extends:
    - .build
    - .base-macos

.test-macos:
  extends:
    - .test
    - .base-macos

.package-macos:
  extends:
    - .package
    - .base-macos

## -----------------------------------------------------------------------------

build-macos-icc:
  extends: .build-macos
  script: scripts/build.py install --compiler icc

test-macos-icc:
  extends: .test-macos
  needs:
    - job: build-macos-icc
      artifacts: true
  script: scripts/test.py

build-macos-clang:
  extends: .build-macos
  script: scripts/build.py install --compiler clang

test-macos-clang:
  extends: .test-macos
  needs:
    - job: build-macos-clang
      artifacts: true
  script: scripts/test.py

build-macos-clang-static:
  extends: .build-macos
  script: scripts/build.py --compiler clang -D OIDN_STATIC_LIB=ON

package-macos:
  extends: .package-macos
  script: scripts/build.py package

## -----------------------------------------------------------------------------
## Windows
## -----------------------------------------------------------------------------

.base-windows:
  extends: .base
  tags:
    - win10
  variables:
    ErrorActionPreference: stop

.build-windows:
  extends:
    - .build
    - .base-windows

.test-windows:
  extends:
    - .test
    - .base-windows

.package-windows:
  extends:
    - .package
    - .base-windows

## -----------------------------------------------------------------------------

build-windows-icc:
  extends: .build-windows
  tags:
    - msvc15
    - icc19
  script: python scripts/build.py install --compiler msvc15-icc19

test-windows-icc-avx512:
  extends: .test-windows
  tags:
    - msvc15
    - icc19
    - avx512vl
  needs:
    - job: build-windows-icc
      artifacts: true
  script: python scripts/test.py

test-windows-icc-avx2:
  extends: .test-windows
  tags:
    - msvc15
    - icc19
    - avx2
  needs:
    - job: build-windows-icc
      artifacts: true
  script: python scripts/test.py

build-windows-msvc15:
  extends: .build-windows
  tags:
    - msvc15
  script: python scripts/build.py --compiler msvc15

build-windows-msvc15-debug:
  extends: .build-windows
  tags:
    - msvc15
  script: python scripts/build.py --compiler msvc15 --config Debug

build-windows-msvc15-static:
  extends: .build-windows
  tags:
    - msvc15
  script: python scripts/build.py --compiler msvc15 -D OIDN_STATIC_LIB=ON

build-windows-msvc16:
  extends: .build-windows
  tags:
    - msvc16
  script: python scripts/build.py install --compiler msvc16

test-windows-msvc16:
  extends: .test-windows
  tags:
    - msvc16
  needs:
    - job: build-windows-msvc16
      artifacts: true
  script: python scripts/test.py

package-windows:
  extends: .package-windows
  tags:
    - msvc15
    - icc19
  script: python scripts/build.py package
      
## -----------------------------------------------------------------------------
## Protex
## -----------------------------------------------------------------------------

scan-protex:
  stage: scan
  tags:
    - docker
  only:
    - schedules
    - web
  script: scripts/protex_scan.sh
  image: amd64/openjdk:8
  dependencies: []
  # Will fail regularly, do not break nightlies because of that.
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - ip_protex.log
    when: always
    expire_in: 1 week
